name       : librime
version    : 1.7.2
release    : 1
source     :
    - https://github.com/rime/librime/archive/refs/tags/1.7.2.tar.gz : 341df211520d44409dfef07401246076f750e82a94e8d60bc2f583e70d7fd6a8
    - git|https://github.com/rime/plum : ff888cbb9fce8c3f5b8b355baeb10685b2052b43
license    : BSD-3-Clause
component  : desktop.library
summary    : Rime Input Method Engine, the core library.
description: |
    Rime Input Method Engine, the core library.
networking : yes
builddeps  :
    - pkgconfig(benchmark) # For leveldb
    - pkgconfig(capnp)
    - pkgconfig(gflags)
    - pkgconfig(gtest)
    - pkgconfig(libglog)
    - pkgconfig(marisa)
    - pkgconfig(opencc)
    - pkgconfig(yaml-cpp)
    - libboost-devel
rundeps    :
    - capnproto # capnproto cannot be detected
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-FTBFS.patch
  
    cp -R $sources/plum.git plum && pushd plum
    %make
    %make_install
    popd

    %cmake_ninja -DENABLE_EXTERNAL_PLUGINS=ON -DBUILD_TEST=OFF -DBOOST_USE_CXX11=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
