name       : librime
version    : 1.7.3
release    : 3
source     :
    - https://github.com/rime/librime/archive/refs/tags/1.7.3.tar.gz : c76b937a27d7b9352c3eea9eb3adaebf70c93457104c7d47d40c006009092c20
license    : BSD-3-Clause
component  : desktop.library
summary    : Rime Input Method Engine, the core library.
description: |
    Rime Input Method Engine, the core library.
builddeps  :
    - pkgconfig(benchmark) # For leveldb
    - pkgconfig(capnp)
    - pkgconfig(gflags)
    - pkgconfig(gtest)
    - pkgconfig(libglog)
    - pkgconfig(marisa)
    - pkgconfig(opencc)
    - pkgconfig(yaml-cpp)
    - libboost-devel
rundeps    :
    - capnproto # capnproto cannot be detected
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-FTBFS.patch

    %cmake_ninja -DENABLE_EXTERNAL_PLUGINS=ON -DINSTALL_PRIVATE_HEADERS=ON -DBUILD_TEST=OFF -DBOOST_USE_CXX11=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
