name       : librime
version    : 1.8.5
release    : 7
source     :
    - https://github.com/rime/librime/archive/refs/tags/1.8.5.tar.gz : 046f3cadae862f94b542864df77531cdbe0f9f6f08cdecc58fd02d20be609a71
license    : BSD-3-Clause
component  : desktop.library
summary    : Rime Input Method Engine, the core library.
description: |
    Rime Input Method Engine, the core library.
builddeps  :
    - pkgconfig(benchmark) # For leveldb
    - pkgconfig(capnp)
    - pkgconfig(gflags)
    - pkgconfig(gtest)
    - pkgconfig(libglog)
    - pkgconfig(marisa)
    - pkgconfig(opencc)
    - pkgconfig(yaml-cpp)
    - libboost-devel
rundeps    :
    - capnproto # capnproto cannot be detected
setup      : |
    %cmake_ninja -DENABLE_EXTERNAL_PLUGINS=ON -DINSTALL_PRIVATE_HEADERS=ON -DBUILD_TEST=OFF -DBOOST_USE_CXX11=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
